// =========================================================================
// DATA RIIL DARI KLIEN (SABA LEMBANG)
// Auto-generated by scripts/process_client_data.py
// Raw Source: assets/real_data_from_client/list produk unggulan marketplace lembang.tsv
// DO NOT MODIFY MANUALLY — Run `uv run scripts/process_client_data.py` to regenerate
// =========================================================================

import { Product } from '../types';

export const REAL_PRODUCTS: Product[] = [
  {
    "id": "real-suntenjaya-kopi-angling",
    "title": "Kopi Arabika Pasir Angling Suntenjaya Kemasan Pouch 200gr",
    "category": "minuman-komoditas",
    "price": 80000,
    "originalPrice": 95000,
    "unit": "/pouch 200gr",
    "villageId": "des-01",
    "villageName": "Desa Wisata Suntenjaya",
    "location": "Pasir Angling, Suntenjaya, Lembang",
    "rating": 5.0,
    "totalReviews": 42,
    "sellerName": "Pa Abdul Mutholib (Pasir Angling Kopi)",
    "sellerBadge": "Petani & Roastery Binaan Resmi",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6287724759068",
    "image": "/images/client/kopi-angling/hero-pouch-v60.webp",
    "gallery": [
      "/images/client/kopi-angling/hero-pouch-v60.webp",
      "/images/client/kopi-angling/drying-greenhouse.webp",
      "/images/client/kopi-angling/coffee-farmers-harvest.webp",
      "/images/client/kopi-angling/coffee-plantation-view.webp",
      "/images/client/kopi-angling/coffee-cherries-tree.webp",
      "/images/client/kopi-angling/coffee-processing-bed.webp",
      "/images/client/kopi-angling/coffee-beans-sample.webp"
    ],
    "description": "Kopi Arabika specialty asli lereng Gunung Palasari Pasir Angling Suntenjaya pada ketinggian 1.400 - 1.700 mdpl. Ditanam organik dengan naungan pohon rimba, dipanen merah matang optimal (full red cherry), serta dijemur dalam solar greenhouse higienis dan di-roasting medium roast dengan profil aroma floral, fruity, dan manis karamel seimbang. Resmi bersertifikat Halal Indonesia ID32110001490620223. Akun Instagram resmi: @pasiranglingkopi_.",
    "highlights": [
      "100% Single Origin Arabika Pasir Angling (1.400-1.700 mdpl)",
      "Sertifikat Halal Resmi ID32110001490620223",
      "Pengeringan Higienis Solar Greenhouse",
      "Medium Roast Karakter Floral & Manis Karamel",
      "Kemasan Alumunium Foil Zipper + Valve Udara"
    ],
    "stockQuota": 150,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 16,
    "verifiedBadge": "Data Riil Mitra Terverifikasi",
    "clientFolderName": "Kopi "
  },
  {
    "id": "real-suntenjaya-camping-angling",
    "title": "Tiket Camping Ground Eduwisata Pasir Angling Suntenjaya",
    "category": "wisata-alam",
    "price": 20000,
    "unit": "/orang/malam",
    "villageId": "des-01",
    "villageName": "Desa Wisata Suntenjaya",
    "location": "Bukit Pasir Angling, Suntenjaya, Lembang",
    "rating": 4.9,
    "totalReviews": 56,
    "sellerName": "Pa Cecep Mulyana (Pengelola Eduwisata)",
    "sellerBadge": "Pengelola Destinasi Desa",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6281517860036",
    "image": "/images/client/pasir-angling/hero-valley-panorama.webp",
    "gallery": [
      "/images/client/pasir-angling/hero-valley-panorama.webp",
      "/images/client/pasir-angling/camping-ridge-view.webp",
      "/images/client/pasir-angling/campsite-mountain-mist.webp",
      "/images/client/pasir-angling/hiking-terrace-trail.webp"
    ],
    "description": "Area perkemahan asri dan tenang di puncak lereng Pasir Angling Suntenjaya (1.400 mdpl) dengan suguhan pemandangan 360 derajat pegunungan Bandung Utara, perkebunan sayur terasering, dan hamparan lautan kabut pagi hari. Dilengkapi fasilitas dasar toilet air gunung bersih, area api unggun, dan pos penjagaan warga.",
    "highlights": [
      "Ketinggian 1.400 mdpl Berhawa Sejuk Segar",
      "Spot Sunrise & Lautan Kabut Mengesankan",
      "Sumber Air Pegunungan Bersih & Toilet Desa",
      "Area Lapang Aman Ramah Keluarga & Komunitas"
    ],
    "facilities": [
      "Toilet Bersih",
      "Sumber Air Bersih",
      "Area Parkir Motor/Mobil",
      "Spot Api Unggun",
      "Warung Warga"
    ],
    "stockQuota": 100,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 7,
    "verifiedBadge": "Data Riil Mitra Terverifikasi",
    "clientFolderName": "Eduwisata Pasir angling 2024"
  },
  {
    "id": "real-suntenjaya-hiking-angling",
    "title": "Tiket & Izin Jalur Hiking Bukit & Perkebunan Pasir Angling",
    "category": "wisata-alam",
    "price": 10000,
    "unit": "/orang",
    "villageId": "des-01",
    "villageName": "Desa Wisata Suntenjaya",
    "location": "Jalur Pasir Angling, Suntenjaya, Lembang",
    "rating": 4.9,
    "totalReviews": 38,
    "sellerName": "Pa Cecep Mulyana (Pengelola Eduwisata)",
    "sellerBadge": "Pengelola Destinasi Desa",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6281517860036",
    "image": "/images/client/pasir-angling/hiking-terrace-trail.webp",
    "gallery": [
      "/images/client/pasir-angling/hero-valley-panorama.webp",
      "/images/client/pasir-angling/hiking-terrace-trail.webp",
      "/images/client/pasir-angling/community-agro-tour.webp",
      "/images/client/pasir-angling/camping-ridge-view.webp",
      "/images/client/pasir-angling/campsite-mountain-mist.webp",
      "/images/client/pasir-angling/trekking-guide-scenic.webp"
    ],
    "description": "Akses lintas alam trekking santai menyusuri jalur pedesaan Suntenjaya melewati kebun kopi arabika naungan, petak sayuran terasering hijau, hingga bibir bukit Pasir Angling. Cocok untuk pegiat jalan pagi, komunitas foto alam, dan keluarga.",
    "highlights": [
      "Jalur Aman dan Terkelola Oleh Warga Lokal",
      "Udara Oksigen Bersih Khas Lereng Gunung Palasari",
      "Pemandangan Terasering Sayur & Kebun Kopi",
      "Ramah Bagi Pemula Maupun Pecinta Trekking"
    ],
    "stockQuota": 200,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 8,
    "verifiedBadge": "Data Riil Mitra Terverifikasi",
    "clientFolderName": "Eduwisata Pasir angling 2024"
  },
  {
    "id": "real-suntenjaya-livein-induksemang",
    "title": "Paket Live-In & Induk Semang Ramah Warga Suntenjaya (2 Hari 1 Malam)",
    "category": "paket-wisata",
    "price": 300000,
    "unit": "/paket/orang",
    "villageId": "des-01",
    "villageName": "Desa Wisata Suntenjaya",
    "location": "Dusun Babakan / Pasir Angling, Suntenjaya, Lembang",
    "rating": 5.0,
    "totalReviews": 29,
    "sellerName": "Pa Abdul Mutholib (Admin Desa / Pokdarwis)",
    "sellerBadge": "Koordinator Live-In Desa",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6287724759068",
    "image": "/images/client/pasir-angling/community-agro-tour.webp",
    "gallery": [
      "/images/client/pasir-angling/community-agro-tour.webp",
      "/images/client/suntenjaya/hero-homestay-teras-kayu.webp",
      "/images/client/suntenjaya/homestay-teras-kebun.webp",
      "/images/client/pasir-angling/hero-valley-panorama.webp",
      "/images/client/pasir-angling/hiking-terrace-trail.webp"
    ],
    "description": "Pengalaman otentik hidup berdampingan bersama keluarga petani Suntenjaya (induk semang). Peserta menginap di rumah warga lokal, mengikuti aktivitas keseharian memetik sayur segar terasering, merawat tanaman kopi arabika, serta menikmati jamuan masakan dapur Sunda tradisional yang hangat.",
    "highlights": [
      "Menginap 1 Malam di Rumah Induk Semang Warga",
      "Makan 3x Menu Tradisional Khas Dapur Pasundan",
      "Aktivitas Pendampingan Tani Kopi & Kebun Sayur",
      "Edukasi Kearifan Lokal & Budaya Gotong Royong"
    ],
    "facilities": [
      "Kamar Bersih di Rumah Warga",
      "Makan 3x Sehari",
      "Pemandu Lokal Warga",
      "Air Hangat Mandi"
    ],
    "itinerary": [
      {
        "time": "14:00",
        "activity": "Penyambutan tamu di Balai Desa & temu induk semang keluarga warga"
      },
      {
        "time": "16:00",
        "activity": "Jalan sore mengitari terasering kebun sayur & interaksi peternak"
      },
      {
        "time": "19:00",
        "activity": "Makan malam bersama keluarga induk semang & bincang budaya"
      },
      {
        "time": "06:00",
        "activity": "Jalan pagi sunrise Pasir Angling & sarapan nasi liwet"
      },
      {
        "time": "08:30",
        "activity": "Praktik petik kopi & kunjungan pengeringan solar greenhouse"
      },
      {
        "time": "12:00",
        "activity": "Makan siang bersama & pelepasan kepulangan"
      }
    ],
    "stockQuota": 30,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 3,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-suntenjaya-homestay-warga",
    "title": "Homestay Rumah Warga Lereng Palasari Suntenjaya (Sewa Kamar / Rumah)",
    "category": "penginapan-lokal",
    "price": 200000,
    "originalPrice": 250000,
    "unit": "/malam",
    "villageId": "des-01",
    "villageName": "Desa Wisata Suntenjaya",
    "location": "Dusun Babakan / Pasir Angling, Suntenjaya, Lembang",
    "rating": 5.0,
    "totalReviews": 35,
    "sellerName": "Paguyuban Homestay & Warga Suntenjaya",
    "sellerBadge": "Tuan Rumah Ramah Desa",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6287724759068",
    "image": "/images/client/suntenjaya/hero-homestay-teras-kayu.webp",
    "gallery": [
      "/images/client/suntenjaya/hero-homestay-teras-kayu.webp",
      "/images/client/suntenjaya/homestay-teras-kebun.webp",
      "/images/client/suntenjaya/homestay-fondasi-batu.webp"
    ],
    "description": "Penginapan sejuk dan tenang di rumah warga lereng Gunung Palasari Suntenjaya (1.290 mdpl). Menikmati udara dingin pegunungan berkabut, pemandangan kebun terasering hijau, teras santai berhias tanaman hias alami, dan keramahan khas pedesaan Pasundan.",
    "highlights": [
      "Udara Dingin Pegunungan Lereng Palasari (1.290 mdpl)",
      "Teras Rumah Asri & Tanaman Hias Dataran Tinggi",
      "Pemandangan Menghadap Kebun Sayur Terasering",
      "Kamar Bersih Nyaman dengan Fasilitas Air Hangat"
    ],
    "facilities": [
      "Kasur Bersih & Selimut Hangat",
      "Kamar Mandi Bersih Air Hangat",
      "Teh Hangat & Kopi Arabika Suntenjaya",
      "Area Parkir Motor & Mobil"
    ],
    "stockQuota": 6,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 3,
    "verifiedBadge": "Data Riil Mitra Terverifikasi",
    "clientFolderName": "20261001/rumah-suntenjaya"
  },
  {
    "id": "real-suntenjaya-tekno-ekologi",
    "title": "Paket Kunjungan Studi Lapangan Tekno-Ekologi Desa Suntenjaya",
    "category": "paket-wisata",
    "price": 300000,
    "unit": "/paket edukasi",
    "villageId": "des-01",
    "villageName": "Desa Wisata Suntenjaya",
    "location": "Kawasan Pertanian Suntenjaya, Lembang",
    "rating": 4.9,
    "totalReviews": 21,
    "sellerName": "Pa Abdul Mutholib (Kelompok Tani Binaan)",
    "sellerBadge": "Instruktur Agrotekno Desa",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6287724759068",
    "image": "/images/client/kopi-angling/drying-greenhouse.webp",
    "gallery": [
      "/images/client/kopi-angling/hero-pouch-v60.webp",
      "/images/client/kopi-angling/drying-greenhouse.webp",
      "/images/client/kopi-angling/coffee-farmers-harvest.webp",
      "/images/client/kopi-angling/coffee-plantation-view.webp",
      "/images/client/kopi-angling/coffee-cherries-tree.webp",
      "/images/client/kopi-angling/coffee-processing-bed.webp",
      "/images/client/kopi-angling/coffee-beans-sample.webp"
    ],
    "description": "Program wisata edukasi terintegrasi teknologi dan ekologi pertanian berkelanjutan. Mempelajari siklus hulu-hilir pertanian ramah lingkungan: pengelolaan pupuk organik biogas peternakan sapi, sistem terasering konservasi tanah miring, hingga pemrosesan pascapanen kopi solar greenhouse.",
    "highlights": [
      "Edukasi Siklus Biogas Limbah Peternakan Menjadi Energi",
      "Teknik Konservasi Lahan Terjal Terasering Sayur",
      "Kunjungan Pemrosesan Kopi Solar Greenhouse Modern",
      "Dipandu Langsung Oleh Praktisi Petani Binaan Desa"
    ],
    "stockQuota": 25,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 13,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-cikole-offroad-landrover-abah",
    "title": "Paket Ekspedisi Offroad Land Rover Rimba Cikole by Abah Dadan",
    "category": "wisata-alam",
    "price": 295000,
    "originalPrice": 350000,
    "unit": "/pax (min 6 orang)",
    "villageId": "des-03",
    "villageName": "Desa Wisata Cikole",
    "location": "Hutan Pinus Cikole - Sukawana - Upas Hill, Lembang",
    "rating": 5.0,
    "totalReviews": 118,
    "sellerName": "Abah Dadan (Pioneer Offroad Cikole)",
    "sellerBadge": "Operator Legenda Terverifikasi",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6281322000600",
    "image": "/images/client/offroad-cikole/hero-abah-dadan-landy.webp",
    "gallery": [
      "/images/client/offroad-cikole/hero-abah-dadan-landy.webp",
      "/images/client/offroad-cikole/mud-splash-adventure.webp",
      "/images/client/offroad-cikole/convoy-pine-trail.webp",
      "/images/client/offroad-cikole/deep-forest-track.webp",
      "/images/client/offroad-cikole/tourist-group-celebration.webp",
      "/images/client/offroad-cikole/cabin-cockpit-view.webp",
      "/images/client/offroad-cikole/action-rocky-trail.webp"
    ],
    "description": "Petualangan jelajah rimba legendaris Cikole menunggangi armada Land Rover 4x4 klasik bersama Abah Dadan & tim berpengalaman. Menerobos trek lumpur ekstrem, jalur bebatuan vulkanik, kubangan air, serta kanopi hutan pinus nan megah. Tersedia 6 pilihan paket rute lengkap mulai Cikole, Tangkuban Parahu Via Upas Hill Track 11, hingga Ciwidey dan Pangalengan.",
    "highlights": [
      "Armada Land Rover 4x4 Klasik Prima Bersertifikat",
      "Termasuk Makan Siang Prasmanan (Buffet Lunch) & Kopi",
      "Termasuk Tiket Masuk Perhutani & Portal Resmi Warga",
      "Opsi Sunrise Upas Hill & Kawah Tangkuban Parahu Jalur 11",
      "Pemandu & Driver Senior Abah Dadan Ramah & Berpengalaman"
    ],
    "facilities": [
      "Armada Land Rover 4x4 + Driver Berpengalaman",
      "Bahan Bakar & Tiket Perhutani + Portal Warga",
      "1x Makan Siang Prasmanan (Buffet Lunch)",
      "1x Coffee Break Tradisional",
      "Air Mineral 330ml",
      "Pertolongan Pertama (P3K) Standar Alam Bebas"
    ],
    "packages": [
      {
        "name": "Package 01: Cikole Land Rover Adventure",
        "price": 295000,
        "unit": "/pax nett",
        "description": "Jelajah offroad rimba pinus Cikole jalur lumpur & bebatuan. Termasuk 1x buffet lunch, 1x coffee break, air mineral, tiket Perhutani & portal warga.",
        "highlights": [
          "Trek Lumpur Hutan Pinus Cikole",
          "Buffet Lunch & Coffee Break",
          "Tiket Perhutani & Portal Masuk"
        ]
      },
      {
        "name": "Package 02: Cikole Adventure & Outbound Fun Games",
        "price": 335000,
        "unit": "/pax nett",
        "description": "Kombinasi offroad Land Rover dan treasure hunt / fun team building games lengkap dengan game master, fasilitator, tools permainan, lunch & coffee break.",
        "highlights": [
          "Offroad + Team Building Games",
          "Game Master & Fasilitator Profesional",
          "Lunch, Coffee Break & Tiket"
        ]
      },
      {
        "name": "Package 03: Upas Hill Sunrise Tangkuban Parahu (Track 11)",
        "price": 435000,
        "unit": "/pax nett",
        "description": "Petualangan sunrise spektakuler joyride menuju Upas Hill menyaksikan bibir kawah Tangkuban Parahu via Track 11. Termasuk lunch, coffee break, dan tiket.",
        "highlights": [
          "Sunrise View Kawah Tangkuban Parahu",
          "Jalur Ikonik Track 11",
          "Makan Siang & Coffee Break"
        ]
      },
      {
        "name": "Package 04: Cikole & Kawah Tangkuban Parahu Normal Route",
        "price": 410000,
        "unit": "/pax nett",
        "description": "Offroad adventure dan kunjungan wisata ke kawah Tangkuban Parahu jalur reguler. Termasuk tiket masuk, buffet lunch, dan coffee break.",
        "highlights": [
          "Offroad + Wisata Kawah Tangkuban Parahu",
          "Tiket Masuk Lengkap",
          "Lunch & Coffee Break"
        ]
      },
      {
        "name": "Package 05: Ciwidey / Rancabali Glamping Lakeside",
        "price": 325000,
        "unit": "/pax nett",
        "description": "Offroad rute perkebunan teh Ciwidey dan kunjungan ke Phinisi Glamping Lakeside. Termasuk tiket perkebunan, portal, lunch, dan coffee break.",
        "highlights": [
          "Offroad Perkebunan Teh Ciwidey",
          "Kunjungan Phinisi Lakeside",
          "Lunch & Coffee Break"
        ]
      },
      {
        "name": "Package 06: Pangalengan Land Rover Adventure",
        "price": 285000,
        "unit": "/pax nett",
        "description": "Petualangan Land Rover membelah perbukitan teh sejuk Pangalengan. Termasuk tiket perkebunan, portal warga, buffet lunch, dan coffee break.",
        "highlights": [
          "Panorama Perkebunan Teh Pangalengan",
          "Trek Tanah Berliku Memacu Adrenalin",
          "Lunch & Coffee Break"
        ]
      }
    ],
    "stockQuota": 50,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 25,
    "verifiedBadge": "Data Riil Mitra Terverifikasi",
    "clientFolderName": "Abah"
  },
  {
    "id": "real-cikole-sewa-armada-landrover",
    "title": "Sewa Privat Armada Land Rover 4x4 Cikole Sukawana (Include Driver & BBM)",
    "category": "wisata-alam",
    "price": 1500000,
    "unit": "/armada/hari",
    "villageId": "des-03",
    "villageName": "Desa Wisata Cikole",
    "location": "Basecamp Land Rover Cikole, Lembang",
    "rating": 4.9,
    "totalReviews": 56,
    "sellerName": "Abah Dadan (Pioneer Offroad Cikole)",
    "sellerBadge": "Operator Legenda Terverifikasi",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6281322000600",
    "image": "/images/client/offroad-cikole/convoy-pine-trail.webp",
    "gallery": [
      "/images/client/offroad-cikole/convoy-pine-trail.webp",
      "/images/client/offroad-cikole/cabin-cockpit-view.webp",
      "/images/client/offroad-cikole/tourist-group-celebration.webp"
    ],
    "description": "Sewa satu armada penuh Land Rover Series 4x4 klasik untuk grup privat atau keluarga (kapasitas 7 penumpang). Termasuk driver lokal handal yang menguasai medan rimba Sukawana-Cikole, bahan bakar, dan dokumentasi foto spot estetik hutan pinus.",
    "highlights": [
      "Kapasitas Privat Maksimal 7 Penumpang / Armada",
      "Termasuk Driver Senior Berpengalaman & Bahan Bakar",
      "Jelajah Bebas Rute Hutan Pinus & Perkebunan Teh",
      "Fleksibel Berhenti di Spot Foto Panorama Alam"
    ],
    "facilities": [
      "1 Unit Land Rover 4x4 Klasik",
      "Driver Senior Berpengalaman",
      "Bahan Bakar Selama Trip",
      "P3K Standar Alam Terbuka"
    ],
    "stockQuota": 12,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 25,
    "verifiedBadge": "Data Riil Mitra Terverifikasi",
    "clientFolderName": "Abah"
  },
  {
    "id": "real-cikole-offroad-ekstrem-sukawana",
    "title": "Paket Joyride Sunrise Upas Hill & Offroad Ekstrem Track 11 Sukawana",
    "category": "wisata-alam",
    "price": 435000,
    "unit": "/pax (min 6 orang)",
    "villageId": "des-03",
    "villageName": "Desa Wisata Cikole",
    "location": "Track 11 Sukawana - Upas Hill Tangkuban Parahu, Cikole",
    "rating": 5.0,
    "totalReviews": 42,
    "sellerName": "Abah Dadan (Pioneer Offroad Cikole)",
    "sellerBadge": "Operator Legenda Terverifikasi",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6281322000600",
    "image": "/images/client/offroad-cikole/mud-splash-adventure.webp",
    "gallery": [
      "/images/client/offroad-cikole/mud-splash-adventure.webp",
      "/images/client/offroad-cikole/action-rocky-trail.webp",
      "/images/client/offroad-cikole/deep-forest-track.webp"
    ],
    "description": "Sensasi menaklukkan rute lumpur terdalam dan bebatuan vulkanik ekstrem Track 11 menuju puncak Upas Hill untuk menyaksikan matahari terbit (sunrise) berlatar megahnya kawah Tangkuban Parahu. Paket petualangan paling memacu adrenalin di Lembang.",
    "highlights": [
      "Sunrise Spektakuler Puncak Upas Hill Tangkuban Parahu",
      "Jalur Ikonik Ekstrem Lumpur Track 11 Sukawana",
      "Termasuk Sarapan Pagi, Coffee Break & Tiket Masuk",
      "Pemandu & Driver Senior Ahli Medan Lumpur Basah"
    ],
    "facilities": [
      "Armada 4x4 Spesifikasi Ekstrem + Driver",
      "BBM, Tiket Masuk Perhutani & Portal",
      "1x Sarapan / Buffet Lunch",
      "1x Coffee Break Hangat",
      "P3K & Asuransi Kegiatan"
    ],
    "stockQuota": 20,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 25,
    "verifiedBadge": "Data Riil Mitra Terverifikasi",
    "clientFolderName": "Abah"
  },
  {
    "id": "real-jayagiri-maguru-kopi",
    "title": "Maguru Kopi Legend Jayagiri (Kopi Robusta & Arabika Pa Maliki)",
    "category": "minuman-komoditas",
    "price": 15000,
    "unit": "/cangkir",
    "villageId": "des-04",
    "villageName": "Desa Wisata Jayagiri",
    "location": "Pos Kopi Jayagiri, Kaki Gunung Tangkuban Parahu",
    "rating": 4.9,
    "totalReviews": 27,
    "sellerName": "Pa Maliki (Maguru Kopi Jayagiri)",
    "sellerBadge": "Pegiat Kopi Jayagiri",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6285717373115",
    "image": "/images/client/jayagiri/hero-maguru-kopi-jayagiri.webp",
    "gallery": [
      "/images/client/jayagiri/hero-maguru-kopi-jayagiri.webp",
      "/images/real/gunung-putri-jayagiri.jpg",
      "/images/real/jayagiri-camping.jpg"
    ],
    "description": "Kopi seduh legendaris di pintu rimba pendakian Jayagiri yang telah menemani penjelajah alam sejak bertahun-tahun. Disajikan langsung oleh Pa Maliki dengan teknik seduh tradisional yang memanjakan penikmat kopi sejati di tengah kabut hutan pinus pegunungan Lembang.",
    "highlights": [
      "Kopi Seduh Otentik Pintu Rimba Jayagiri",
      "Pilihan Arabika Jayagiri & Robusta Tubruk Tradisional",
      "Suasana Warung Kayu Sejuk Teduh di Hutan Pinus",
      "Disajikan Hangat Pas Menemani Suhu Dingin Pegunungan"
    ],
    "stockQuota": 60,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 43,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-gudangkahuripan-gamelan-budaya",
    "title": "Workshop Seni Gamelan Sunda, Tari Tradisional & Literasi Kearifan Lokal",
    "category": "paket-wisata",
    "price": 100000,
    "unit": "/peserta",
    "villageId": "des-07",
    "villageName": "Desa Wisata Gudangkahuripan",
    "location": "Sanggar Seni Budaya Gudangkahuripan, Lembang",
    "rating": 5.0,
    "totalReviews": 31,
    "sellerName": "Pa Mei Wisana (Budayawan Gudangkahuripan)",
    "sellerBadge": "Ketua Sanggar Seni Terverifikasi",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6281221520514",
    "image": "/images/client/gudangkahuripan/hero-tari-jaipong-materi.webp",
    "gallery": [
      "/images/client/gudangkahuripan/hero-tari-jaipong-materi.webp",
      "/images/client/gudangkahuripan/jaipong-peserta-senyum.webp",
      "/images/client/gudangkahuripan/jaipong-pelatihan-kompak.webp",
      "/images/client/gudangkahuripan/jaipong-kebersamaan.webp",
      "/images/client/gudangkahuripan/jaipong-praktek-lapangan.webp",
      "/images/client/gudangkahuripan/jaipong-gerak-dasar.webp"
    ],
    "description": "Kelas apresiasi seni dan budaya Pasundan interaktif yang dipandu langsung oleh budayawan senior Pa Mei Wisana. Peserta diajak praktik memainkan seperangkat instrumen gamelan degung/salendro, mengenal gerak dasar tari Jaipong, serta menyimak narasi filosofi kearifan lokal masyarakat Lembang zaman ke zaman.",
    "highlights": [
      "Praktik Langsung Menabuh Gamelan Degung Sunda Asli",
      "Pengenalan Gerak Dasar Tari Tradisional Pasundan",
      "Sesi Bincang Literasi Sejarah & Nilai Budaya Lokal",
      "Didampingi Pengrawit & Seniman Senior Desa"
    ],
    "stockQuota": 40,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 53,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-wangunsari-tahu-susu",
    "title": "Tahu Susu Lembut Asli Wangunsari (1 Kemasan Isi 10 Pcs)",
    "category": "kuliner",
    "price": 5000,
    "unit": "/kemasan (10 pcs)",
    "villageId": "des-05",
    "villageName": "Desa Wisata Wangunsari",
    "location": "Sentra Tahu Susu Wangunsari, Lembang",
    "rating": 5.0,
    "totalReviews": 65,
    "sellerName": "Pa Agus (Sentra Tahu Susu Wangunsari)",
    "sellerBadge": "Produsen Tahu Susu Binaan",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6285221738102",
    "image": "/images/client/wangunsari/tahu-susu-agus-kemasan-10pcs.webp",
    "gallery": [
      "/images/client/wangunsari/tahu-susu-agus-kemasan-10pcs.webp",
      "/images/client/wangunsari/tahu-susu-nampan-produksi.webp",
      "/images/client/wangunsari/tahu-susu-cetakan-potong.webp",
      "/images/client/wangunsari/tahu-susu-proses-kemas.webp",
      "/images/client/wangunsari/tahu-susu-segar.webp",
      "/images/client/wangunsari/tahu-susu-goreng-panas.webp"
    ],
    "description": "Tahu susu legendaris produksi Pa Agus Wangunsari Lembang yang terkenal sangat lembut di dalam dan garing renyah di luar saat digoreng. Dibuat dari kedelai non-transgenik pilihan yang dipadukan dengan susu sapi murni segar hasil peternak lokal. Tanpa bahan pengawet. Kemasan plastik higienis berlabel Tahu Agus isi 10 pcs dengan harga sangat terjangkau Rp 5.000 per kemasan.",
    "highlights": [
      "Harga Sangat Terjangkau Rp 5.000 / Kemasan (10 Pcs)",
      "Tekstur Lumer Lembut di Dalam, Garing di Luar",
      "Kandungan Susu Sapi Murni Segar Asli Lembang",
      "Higienis & Bebas Pengawet Berbahaya",
      "Cocok Sebagai Camilan Gurih & Oleh-Oleh Wajib"
    ],
    "stockQuota": 100,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 62,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-wangunsari-kicimpring",
    "title": "Kicimpring Singkong Renyah Gurih Wangunsari (250gr)",
    "category": "kuliner",
    "price": 15000,
    "unit": "/bungkus 250gr",
    "villageId": "des-05",
    "villageName": "Desa Wisata Wangunsari",
    "location": "Wangunsari, Lembang",
    "rating": 4.9,
    "totalReviews": 39,
    "sellerName": "Bu Agustian (UMKM Olahan Singkong)",
    "sellerBadge": "Pengrajin Kicimpring Tradisional",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6282216508602",
    "image": "/images/client/wangunsari/kicimpring-singkong-renyah.webp",
    "gallery": [
      "/images/client/wangunsari/kicimpring-singkong-renyah.webp",
      "/images/client/wangunsari/kicimpring-jemur-tradisional.webp",
      "/images/client/wangunsari/kicimpring-produksi-warga.webp"
    ],
    "description": "Kerupuk kicimpring olahan singkong khas Pasundan buatan tangan Bu Agustian di Desa Wangunsari. Dipadukan dengan rempah daun bawang, bawang putih, ketumbar, dan cabai merah yang menghasilkan kerenyahan tiada tara dengan cita rasa gurih nagih.",
    "highlights": [
      "100% Singkong Lokal Berkualitas",
      "Bumbu Rempah Daun Bawang Alami",
      "Sangat Renyah, Tidak Keras",
      "Camilan Tradisional Favorit Sepanjang Masa"
    ],
    "stockQuota": 80,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 63,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-wangunsari-ranginang",
    "title": "Ranginang Ketan Rasa Terasi Dapur Bu Entin (1 Kg)",
    "category": "kuliner",
    "price": 65000,
    "unit": "/kg (+- 50 pcs)",
    "villageId": "des-05",
    "villageName": "Desa Wisata Wangunsari",
    "location": "Wangunsari, Lembang",
    "rating": 4.8,
    "totalReviews": 34,
    "sellerName": "Bu Entin (Dapur Ranginang Wangunsari)",
    "sellerBadge": "Pengrajin Ranginang Tradisional",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6287887614185",
    "image": "/images/client/wangunsari/ranginang-terasi-khas-wangunsari.webp",
    "gallery": [
      "/images/client/wangunsari/ranginang-terasi-khas-wangunsari.webp",
      "/images/client/wangunsari/ranginang-mentah-terasi.webp",
      "/images/client/wangunsari/ranginang-goreng-mekar.webp",
      "/images/client/wangunsari/ranginang-tampah-jemur.webp"
    ],
    "description": "Ranginang beras ketan premium pilihan rasa terasi gurih khas Sunda buatan Dapur Bu Entin Wangunsari. Keterangan produk: rasa terasi gurih, kemasan 1 kg (kurang lebih 50 pcs) dengan harga Rp 65.000/kg. Mekar sempurna saat digoreng, super renyah tanpa meninggalkan rasa lengket di gigi.",
    "highlights": [
      "Rasa Terasi Gurih Alami Khas Pasundan",
      "Kemasan 1 Kg (+- 50 Pcs) Rp 65.000",
      "Beras Ketan Pilihan Hasil Panen Petani",
      "Mekar Sempurna & Renyah Maksimal",
      "Tersedia Siap Santap Maupun Mentah"
    ],
    "stockQuota": 60,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 64,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-wangunsari-peuyeum-ketan",
    "title": "Peuyeum Ketan Daun Jambu Wangunsari (Sistem PO)",
    "category": "kuliner",
    "price": 25000,
    "unit": "/ember mini (isi 16 pcs)",
    "villageId": "des-05",
    "villageName": "Desa Wisata Wangunsari",
    "location": "Wangunsari, Lembang",
    "rating": 5.0,
    "totalReviews": 45,
    "sellerName": "Pa Agus Komarudin (Peuyeum Ketan Tradisional)",
    "sellerBadge": "Pembuat Peuyeum Tradisional",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "6285222431566",
    "image": "/images/client/wangunsari/peuyeum-ketan-daun-jambu.webp",
    "gallery": [
      "/images/client/wangunsari/peuyeum-ketan-daun-jambu.webp"
    ],
    "description": "Tape ketan (peuyeum) hitam fermentasi alami yang dibungkus rapi menggunakan daun jambu air segar. Memiliki rasa manis berair (juicy), aroma khas ragi tradisional yang segar, serta tekstur lembut yang nikmat disajikan dingin. Keterangan Pemesanan: Sistem PO (Pre-Order), minimal 4 hari sebelumnya. Pemesanan hanya bisa dilakukan pada hari Sabtu dan Minggu.",
    "highlights": [
      "Sistem PO Min. 4 Hari (Pemesanan Hari Sabtu & Minggu)",
      "Fermentasi Ragi Alami Resep Turun-Temurun",
      "Wangi Daun Jambu Air Segar Alami",
      "Air Tape Manis Segar Menyegarkan Tenggorokan",
      "Dikemas Higienis Ember Mini Praktis & Aman Dibawa"
    ],
    "stockQuota": 50,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 65,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-sukajaya-yoghurt-alami",
    "title": "Yoghurt Probiotik Aneka Rasa Toko Barokah Pa Emin (Botol 250ml)",
    "category": "olahan-susu",
    "price": 18000,
    "unit": "/botol 250ml",
    "villageId": "des-08",
    "villageName": "Desa Wisata Sukajaya",
    "location": "Sentra Olahan Susu Barokah, Sukajaya, Lembang",
    "rating": 4.9,
    "totalReviews": 52,
    "sellerName": "Pa Emin (Toko Barokah Sukajaya)",
    "sellerBadge": "Peternak & Pengolah Susu Sukajaya",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "62895322096504",
    "image": "/images/client/sukajaya/hero-yoghvit-botol.webp",
    "gallery": [
      "/images/client/sukajaya/hero-yoghvit-botol.webp",
      "/images/client/sukajaya/yoghurt-stick-mat-pochi.webp",
      "/images/client/sukajaya/hero-toko-barokah-susu-murni.webp"
    ],
    "description": "Yoghurt kental kaya probiotik baik (Yoghvit & Stick Mat Pochi) yang diolah langsung dari 100% susu sapi perah segar peternak Sukajaya di Toko Barokah Pa Emin. Tanpa pewarna sintetis atau pemanis buatan, tersedia dalam varian rasa buah segar leci, durian, anggur, dan aneka buah.",
    "highlights": [
      "Produksi Asli Toko Barokah Pa Emin Sukajaya",
      "Dibuat Dari Susu Sapi Segar Perahan Pagi",
      "Kaya Bakteri Baik Probiotik Menyehatkan Pencernaan",
      "Varian Yoghvit Botol & Stick Yoghurt Mat Pochi",
      "Kemasan Higienis Bersertifikasi Resmi"
    ],
    "stockQuota": 80,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 69,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-sukajaya-susu-murni-segar",
    "title": "Susu Sapi Murni Segar Pasteur Toko Barokah Pa Emin (Botol 1 Liter)",
    "category": "olahan-susu",
    "price": 15000,
    "unit": "/liter",
    "villageId": "des-08",
    "villageName": "Desa Wisata Sukajaya",
    "location": "Toko Barokah, Sukajaya, Lembang",
    "rating": 5.0,
    "totalReviews": 61,
    "sellerName": "Pa Emin (Toko Barokah Sukajaya)",
    "sellerBadge": "Peternak & Pengolah Susu Sukajaya",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "62895322096504",
    "image": "/images/client/sukajaya/hero-toko-barokah-susu-murni.webp",
    "gallery": [
      "/images/client/sukajaya/hero-toko-barokah-susu-murni.webp",
      "/images/client/sukajaya/hero-yoghvit-botol.webp"
    ],
    "description": "Susu sapi segar murni hasil perahan harian peternak sapi perah lereng Sukajaya yang dipasarkan langsung melalui Toko Barokah Pa Emin. Telah melalui pasteurisasi suhu terjaga untuk menjamin kehigienisan tanpa mengurangi kelezatan rasa gurih alami dan nutrisi alaminya.",
    "highlights": [
      "Susu Perah Segar Murni Toko Barokah Pa Emin",
      "Pasteurisasi Higienis Aman Dikonsumsi Segera",
      "Tinggi Kalsium, Lemak Baik & Protein Alami",
      "Pengiriman Cepat Terjaga Suhu Dingin"
    ],
    "stockQuota": 100,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 70,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-sukajaya-tahu-susu",
    "title": "Tahu Susu Lembut Barokah Sukajaya by Pa Emin (1 Kotak)",
    "category": "kuliner",
    "price": 25000,
    "unit": "/kotak",
    "villageId": "des-08",
    "villageName": "Desa Wisata Sukajaya",
    "location": "Kp. Citespong, Sukajaya, Lembang",
    "rating": 4.8,
    "totalReviews": 37,
    "sellerName": "Pa Emin (Toko Barokah Sukajaya)",
    "sellerBadge": "Peternak & Pengolah Susu Sukajaya",
    "sellerAvatar": "/images/default-avatar.svg",
    "sellerPhone": "62895322096504",
    "image": "/images/client/sukajaya/hero-tahu-susu-barokah.webp",
    "gallery": [
      "/images/client/sukajaya/hero-tahu-susu-barokah.webp",
      "/images/client/sukajaya/hero-toko-barokah-susu-murni.webp"
    ],
    "description": "Tahu susu lezat khas Sukajaya buatan Tahu Susu Barokah (Pa Emin) di Kp. Citespong RT 02 RW 02 Desa Sukajaya. Memadukan sari kedelai gurih dan susu sapi segar murni tanpa bahan pengawet. Resmi terdaftar Halal dan NIB 5122300062931.",
    "highlights": [
      "Tahu Susu Barokah Pa Emin Citespong Sukajaya",
      "Bersertifikat Halal & NIB Resmi 5122300062931",
      "Campuran Susu Murni Peternak Sukajaya",
      "Luar Garing Renyah, Dalam Sangat Lembut Lumer"
    ],
    "stockQuota": 75,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 71,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  }
];
