// =========================================================================
// DATA RIIL DARI KLIEN (SABA LEMBANG)
// Auto-generated by scripts/process_client_data.py
// Raw Source: assets/real_data_from_client/list produk unggulan marketplace lembang.tsv
// DO NOT MODIFY MANUALLY — Run `uv run scripts/process_client_data.py` to regenerate
// =========================================================================

import { Product } from '../types';

export const REAL_PRODUCTS: Product[] = [
  {
    "id": "real-suntenjaya-kopi-angling",
    "title": "Kopi Arabika Pasir Angling Suntenjaya Kemasan Pouch 200gr",
    "category": "minuman-komoditas",
    "price": 80000,
    "originalPrice": 95000,
    "unit": "/pouch 200gr",
    "villageId": "des-01",
    "villageName": "Desa Wisata Suntenjaya",
    "location": "Pasir Angling, Suntenjaya, Lembang",
    "rating": 5.0,
    "totalReviews": 42,
    "sellerName": "Pa Abdul Mutholib (Pasir Angling Kopi)",
    "sellerBadge": "Petani & Roastery Binaan Resmi",
    "sellerAvatar": "/images/client/kopi-angling/coffee-plantation-view.webp",
    "sellerPhone": "6287724759068",
    "image": "/images/client/kopi-angling/hero-pouch-v60.webp",
    "gallery": [
      "/images/client/kopi-angling/hero-pouch-v60.webp",
      "/images/client/kopi-angling/drying-greenhouse.webp",
      "/images/client/kopi-angling/coffee-farmers-harvest.webp",
      "/images/client/kopi-angling/coffee-plantation-view.webp",
      "/images/client/kopi-angling/coffee-cherries-tree.webp",
      "/images/client/kopi-angling/coffee-processing-bed.webp",
      "/images/client/kopi-angling/coffee-beans-sample.webp"
    ],
    "description": "Kopi Arabika specialty asli lereng Gunung Palasari Pasir Angling Suntenjaya pada ketinggian 1.400 - 1.700 mdpl. Ditanam organik dengan naungan pohon rimba, dipanen merah matang optimal (full red cherry), serta dijemur dalam solar greenhouse higienis dan di-roasting medium roast dengan profil aroma floral, fruity, dan manis karamel seimbang. Resmi bersertifikat Halal Indonesia ID32110001490620223. Akun Instagram resmi: @pasiranglingkopi_.",
    "highlights": [
      "100% Single Origin Arabika Pasir Angling (1.400-1.700 mdpl)",
      "Sertifikat Halal Resmi ID32110001490620223",
      "Pengeringan Higienis Solar Greenhouse",
      "Medium Roast Karakter Floral & Manis Karamel",
      "Kemasan Alumunium Foil Zipper + Valve Udara"
    ],
    "stockQuota": 150,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 16,
    "verifiedBadge": "Data Riil Mitra Terverifikasi",
    "clientFolderName": "Kopi "
  },
  {
    "id": "real-suntenjaya-camping-angling",
    "title": "Tiket Camping Ground Eduwisata Pasir Angling Suntenjaya",
    "category": "wisata-alam",
    "price": 20000,
    "unit": "/orang/malam",
    "villageId": "des-01",
    "villageName": "Desa Wisata Suntenjaya",
    "location": "Bukit Pasir Angling, Suntenjaya, Lembang",
    "rating": 4.9,
    "totalReviews": 56,
    "sellerName": "Pa Cecep Mulyana (Pengelola Eduwisata)",
    "sellerBadge": "Pengelola Destinasi Desa",
    "sellerAvatar": "/images/unsplash/photo-1500648767791-00dcc994a43e_w200.jpg",
    "sellerPhone": "6281517860036",
    "image": "/images/client/pasir-angling/hero-valley-panorama.webp",
    "gallery": [
      "/images/client/pasir-angling/hero-valley-panorama.webp",
      "/images/client/pasir-angling/camping-ridge-view.webp",
      "/images/client/pasir-angling/campsite-mountain-mist.webp",
      "/images/client/pasir-angling/hiking-terrace-trail.webp"
    ],
    "description": "Area perkemahan asri dan tenang di puncak lereng Pasir Angling Suntenjaya (1.400 mdpl) dengan suguhan pemandangan 360 derajat pegunungan Bandung Utara, perkebunan sayur terasering, dan hamparan lautan kabut pagi hari. Dilengkapi fasilitas dasar toilet air gunung bersih, area api unggun, dan pos penjagaan warga.",
    "highlights": [
      "Ketinggian 1.400 mdpl Berhawa Sejuk Segar",
      "Spot Sunrise & Lautan Kabut Mengesankan",
      "Sumber Air Pegunungan Bersih & Toilet Desa",
      "Area Lapang Aman Ramah Keluarga & Komunitas"
    ],
    "facilities": [
      "Toilet Bersih",
      "Sumber Air Bersih",
      "Area Parkir Motor/Mobil",
      "Spot Api Unggun",
      "Warung Warga"
    ],
    "stockQuota": 100,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 7,
    "verifiedBadge": "Data Riil Mitra Terverifikasi",
    "clientFolderName": "Eduwisata Pasir angling 2024"
  },
  {
    "id": "real-suntenjaya-hiking-angling",
    "title": "Tiket & Izin Jalur Hiking Bukit & Perkebunan Pasir Angling",
    "category": "wisata-alam",
    "price": 10000,
    "unit": "/orang",
    "villageId": "des-01",
    "villageName": "Desa Wisata Suntenjaya",
    "location": "Jalur Pasir Angling, Suntenjaya, Lembang",
    "rating": 4.9,
    "totalReviews": 38,
    "sellerName": "Pa Cecep Mulyana (Pengelola Eduwisata)",
    "sellerBadge": "Pengelola Destinasi Desa",
    "sellerAvatar": "/images/unsplash/photo-1500648767791-00dcc994a43e_w200.jpg",
    "sellerPhone": "6281517860036",
    "image": "/images/client/pasir-angling/hiking-terrace-trail.webp",
    "gallery": [
      "/images/client/pasir-angling/hero-valley-panorama.webp",
      "/images/client/pasir-angling/hiking-terrace-trail.webp",
      "/images/client/pasir-angling/community-agro-tour.webp",
      "/images/client/pasir-angling/camping-ridge-view.webp",
      "/images/client/pasir-angling/campsite-mountain-mist.webp",
      "/images/client/pasir-angling/trekking-guide-scenic.webp"
    ],
    "description": "Akses lintas alam trekking santai menyusuri jalur pedesaan Suntenjaya melewati kebun kopi arabika naungan, petak sayuran terasering hijau, hingga bibir bukit Pasir Angling. Cocok untuk pegiat jalan pagi, komunitas foto alam, dan keluarga.",
    "highlights": [
      "Jalur Aman dan Terkelola Oleh Warga Lokal",
      "Udara Oksigen Bersih Khas Lereng Gunung Palasari",
      "Pemandangan Terasering Sayur & Kebun Kopi",
      "Ramah Bagi Pemula Maupun Pecinta Trekking"
    ],
    "stockQuota": 200,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 8,
    "verifiedBadge": "Data Riil Mitra Terverifikasi",
    "clientFolderName": "Eduwisata Pasir angling 2024"
  },
  {
    "id": "real-suntenjaya-livein-induksemang",
    "title": "Paket Live-In & Induk Semang Ramah Warga Suntenjaya (2 Hari 1 Malam)",
    "category": "paket-wisata",
    "price": 300000,
    "unit": "/paket/orang",
    "villageId": "des-01",
    "villageName": "Desa Wisata Suntenjaya",
    "location": "Dusun Babakan / Pasir Angling, Suntenjaya, Lembang",
    "rating": 5.0,
    "totalReviews": 29,
    "sellerName": "Pa Abdul Mutholib (Admin Desa / Pokdarwis)",
    "sellerBadge": "Koordinator Live-In Desa",
    "sellerAvatar": "/images/unsplash/photo-1507003211169-0a1dd7228f2d_w200.jpg",
    "sellerPhone": "6287724759068",
    "image": "/images/client/pasir-angling/community-agro-tour.webp",
    "gallery": [
      "/images/client/pasir-angling/hero-valley-panorama.webp",
      "/images/client/pasir-angling/hiking-terrace-trail.webp",
      "/images/client/pasir-angling/community-agro-tour.webp",
      "/images/client/pasir-angling/camping-ridge-view.webp",
      "/images/client/pasir-angling/campsite-mountain-mist.webp",
      "/images/client/pasir-angling/trekking-guide-scenic.webp"
    ],
    "description": "Pengalaman otentik hidup berdampingan bersama keluarga petani Suntenjaya (induk semang). Peserta menginap di rumah warga lokal, mengikuti aktivitas keseharian memetik sayur segar terasering, merawat tanaman kopi arabika, serta menikmati jamuan masakan dapur Sunda tradisional yang hangat.",
    "highlights": [
      "Menginap 1 Malam di Rumah Induk Semang Warga",
      "Makan 3x Menu Tradisional Khas Dapur Pasundan",
      "Aktivitas Pendampingan Tani Kopi & Kebun Sayur",
      "Edukasi Kearifan Lokal & Budaya Gotong Royong"
    ],
    "facilities": [
      "Kamar Bersih di Rumah Warga",
      "Makan 3x Sehari",
      "Pemandu Lokal Warga",
      "Air Hangat Mandi"
    ],
    "itinerary": [
      {
        "time": "14:00",
        "activity": "Penyambutan tamu di Balai Desa & temu induk semang keluarga warga"
      },
      {
        "time": "16:00",
        "activity": "Jalan sore mengitari terasering kebun sayur & interaksi peternak"
      },
      {
        "time": "19:00",
        "activity": "Makan malam bersama keluarga induk semang & bincang budaya"
      },
      {
        "time": "06:00",
        "activity": "Jalan pagi sunrise Pasir Angling & sarapan nasi liwet"
      },
      {
        "time": "08:30",
        "activity": "Praktik petik kopi & kunjungan pengeringan solar greenhouse"
      },
      {
        "time": "12:00",
        "activity": "Makan siang bersama & pelepasan kepulangan"
      }
    ],
    "stockQuota": 30,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 3,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-suntenjaya-tekno-ekologi",
    "title": "Paket Kunjungan Studi Lapangan Tekno-Ekologi Desa Suntenjaya",
    "category": "paket-wisata",
    "price": 300000,
    "unit": "/paket edukasi",
    "villageId": "des-01",
    "villageName": "Desa Wisata Suntenjaya",
    "location": "Kawasan Pertanian Suntenjaya, Lembang",
    "rating": 4.9,
    "totalReviews": 21,
    "sellerName": "Pa Abdul Mutholib (Kelompok Tani Binaan)",
    "sellerBadge": "Instruktur Agrotekno Desa",
    "sellerAvatar": "/images/unsplash/photo-1507003211169-0a1dd7228f2d_w200.jpg",
    "sellerPhone": "6287724759068",
    "image": "/images/client/kopi-angling/drying-greenhouse.webp",
    "gallery": [
      "/images/client/kopi-angling/hero-pouch-v60.webp",
      "/images/client/kopi-angling/drying-greenhouse.webp",
      "/images/client/kopi-angling/coffee-farmers-harvest.webp",
      "/images/client/kopi-angling/coffee-plantation-view.webp",
      "/images/client/kopi-angling/coffee-cherries-tree.webp",
      "/images/client/kopi-angling/coffee-processing-bed.webp",
      "/images/client/kopi-angling/coffee-beans-sample.webp"
    ],
    "description": "Program wisata edukasi terintegrasi teknologi dan ekologi pertanian berkelanjutan. Mempelajari siklus hulu-hilir pertanian ramah lingkungan: pengelolaan pupuk organik biogas peternakan sapi, sistem terasering konservasi tanah miring, hingga pemrosesan pascapanen kopi solar greenhouse.",
    "highlights": [
      "Edukasi Siklus Biogas Limbah Peternakan Menjadi Energi",
      "Teknik Konservasi Lahan Terjal Terasering Sayur",
      "Kunjungan Pemrosesan Kopi Solar Greenhouse Modern",
      "Dipandu Langsung Oleh Praktisi Petani Binaan Desa"
    ],
    "stockQuota": 25,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 13,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-cikole-offroad-landrover-abah",
    "title": "Paket Ekspedisi Offroad Land Rover Rimba Cikole by Abah Dadan",
    "category": "wisata-alam",
    "price": 295000,
    "originalPrice": 350000,
    "unit": "/pax (min 6 orang)",
    "villageId": "des-03",
    "villageName": "Desa Wisata Cikole",
    "location": "Hutan Pinus Cikole - Sukawana - Upas Hill, Lembang",
    "rating": 5.0,
    "totalReviews": 118,
    "sellerName": "Abah Dadan (Pioneer Offroad Cikole)",
    "sellerBadge": "Operator Legenda Terverifikasi",
    "sellerAvatar": "/images/client/offroad-cikole/hero-abah-dadan-landy.webp",
    "sellerPhone": "6281322000600",
    "image": "/images/client/offroad-cikole/hero-abah-dadan-landy.webp",
    "gallery": [
      "/images/client/offroad-cikole/hero-abah-dadan-landy.webp",
      "/images/client/offroad-cikole/mud-splash-adventure.webp",
      "/images/client/offroad-cikole/convoy-pine-trail.webp",
      "/images/client/offroad-cikole/deep-forest-track.webp",
      "/images/client/offroad-cikole/tourist-group-celebration.webp",
      "/images/client/offroad-cikole/cabin-cockpit-view.webp",
      "/images/client/offroad-cikole/action-rocky-trail.webp"
    ],
    "description": "Petualangan jelajah rimba legendaris Cikole menunggangi armada Land Rover 4x4 klasik bersama Abah Dadan & tim berpengalaman. Menerobos trek lumpur ekstrem, jalur bebatuan vulkanik, kubangan air, serta kanopi hutan pinus nan megah. Tersedia 6 pilihan paket rute lengkap mulai Cikole, Tangkuban Parahu Via Upas Hill Track 11, hingga Ciwidey dan Pangalengan.",
    "highlights": [
      "Armada Land Rover 4x4 Klasik Prima Bersertifikat",
      "Termasuk Makan Siang Prasmanan (Buffet Lunch) & Kopi",
      "Termasuk Tiket Masuk Perhutani & Portal Resmi Warga",
      "Opsi Sunrise Upas Hill & Kawah Tangkuban Parahu Jalur 11",
      "Pemandu & Driver Senior Abah Dadan Ramah & Berpengalaman"
    ],
    "facilities": [
      "Armada Land Rover 4x4 + Driver Berpengalaman",
      "Bahan Bakar & Tiket Perhutani + Portal Warga",
      "1x Makan Siang Prasmanan (Buffet Lunch)",
      "1x Coffee Break Tradisional",
      "Air Mineral 330ml",
      "Pertolongan Pertama (P3K) Standar Alam Bebas"
    ],
    "packages": [
      {
        "name": "Package 01: Cikole Land Rover Adventure",
        "price": 295000,
        "unit": "/pax nett",
        "description": "Jelajah offroad rimba pinus Cikole jalur lumpur & bebatuan. Termasuk 1x buffet lunch, 1x coffee break, air mineral, tiket Perhutani & portal warga.",
        "highlights": [
          "Trek Lumpur Hutan Pinus Cikole",
          "Buffet Lunch & Coffee Break",
          "Tiket Perhutani & Portal Masuk"
        ]
      },
      {
        "name": "Package 02: Cikole Adventure & Outbound Fun Games",
        "price": 335000,
        "unit": "/pax nett",
        "description": "Kombinasi offroad Land Rover dan treasure hunt / fun team building games lengkap dengan game master, fasilitator, tools permainan, lunch & coffee break.",
        "highlights": [
          "Offroad + Team Building Games",
          "Game Master & Fasilitator Profesional",
          "Lunch, Coffee Break & Tiket"
        ]
      },
      {
        "name": "Package 03: Upas Hill Sunrise Tangkuban Parahu (Track 11)",
        "price": 435000,
        "unit": "/pax nett",
        "description": "Petualangan sunrise spektakuler joyride menuju Upas Hill menyaksikan bibir kawah Tangkuban Parahu via Track 11. Termasuk lunch, coffee break, dan tiket.",
        "highlights": [
          "Sunrise View Kawah Tangkuban Parahu",
          "Jalur Ikonik Track 11",
          "Makan Siang & Coffee Break"
        ]
      },
      {
        "name": "Package 04: Cikole & Kawah Tangkuban Parahu Normal Route",
        "price": 410000,
        "unit": "/pax nett",
        "description": "Offroad adventure dan kunjungan wisata ke kawah Tangkuban Parahu jalur reguler. Termasuk tiket masuk, buffet lunch, dan coffee break.",
        "highlights": [
          "Offroad + Wisata Kawah Tangkuban Parahu",
          "Tiket Masuk Lengkap",
          "Lunch & Coffee Break"
        ]
      },
      {
        "name": "Package 05: Ciwidey / Rancabali Glamping Lakeside",
        "price": 325000,
        "unit": "/pax nett",
        "description": "Offroad rute perkebunan teh Ciwidey dan kunjungan ke Phinisi Glamping Lakeside. Termasuk tiket perkebunan, portal, lunch, dan coffee break.",
        "highlights": [
          "Offroad Perkebunan Teh Ciwidey",
          "Kunjungan Phinisi Lakeside",
          "Lunch & Coffee Break"
        ]
      },
      {
        "name": "Package 06: Pangalengan Land Rover Adventure",
        "price": 285000,
        "unit": "/pax nett",
        "description": "Petualangan Land Rover membelah perbukitan teh sejuk Pangalengan. Termasuk tiket perkebunan, portal warga, buffet lunch, dan coffee break.",
        "highlights": [
          "Panorama Perkebunan Teh Pangalengan",
          "Trek Tanah Berliku Memacu Adrenalin",
          "Lunch & Coffee Break"
        ]
      }
    ],
    "stockQuota": 50,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 25,
    "verifiedBadge": "Data Riil Mitra Terverifikasi",
    "clientFolderName": "Abah"
  },
  {
    "id": "real-cikole-green-grass",
    "title": "Tiket Masuk & Wahana Alam Green Grass Cikole (GGC)",
    "category": "wisata-alam",
    "price": 35000,
    "unit": "/orang",
    "villageId": "des-03",
    "villageName": "Desa Wisata Cikole",
    "location": "Kawasan Wisata Green Grass Cikole, Lembang",
    "rating": 4.8,
    "totalReviews": 49,
    "sellerName": "Manajemen Green Grass Cikole (GGC)",
    "sellerBadge": "Pengelola Wisata Alam Resmi",
    "sellerAvatar": "/images/unsplash/photo-1507003211169-0a1dd7228f2d_w200.jpg",
    "sellerPhone": "6281909605127",
    "image": "/images/unsplash/photo-1448375240586-882707db888b_w1200.jpg",
    "gallery": [
      "/images/unsplash/photo-1448375240586-882707db888b_w1200.jpg",
      "/images/unsplash/photo-1513836279014-a89f7a76ae86_w1200.jpg"
    ],
    "description": "Destinasi wisata hijau terbuka di tengah rimbunnya hutan pinus Cikole Lembang. Menyediakan padang rumput alami untuk piknik keluarga, gathering komunitas, spot foto estetik, dan area relaksasi berudara pegunungan segar.",
    "highlights": [
      "Hamparan Padang Rumput Segar Hutan Pinus",
      "Lokasi Strategis di Jalur Wisata Utama Cikole",
      "Fasilitas Toilet Bersih, Mushola, & Kafetaria",
      "Cocok Untuk Piknik Keluarga & Foto Instagramable"
    ],
    "stockQuota": 150,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 24,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-cikole-maguru-kopi",
    "title": "Kopi Seduh Maguru Legend Cikole (Single Origin Hutan Cikole)",
    "category": "minuman-komoditas",
    "price": 15000,
    "unit": "/cangkir",
    "villageId": "des-03",
    "villageName": "Desa Wisata Cikole",
    "location": "Kedai Maguru Kopi, Cikole, Lembang",
    "rating": 4.9,
    "totalReviews": 33,
    "sellerName": "Kedai Maguru Kopi Cikole",
    "sellerBadge": "Kedai Kopi Legend Lokal",
    "sellerAvatar": "/images/unsplash/photo-1500648767791-00dcc994a43e_w200.jpg",
    "sellerPhone": "6281221885527",
    "image": "/images/unsplash/photo-1514432324607-a09d9b4aefdd_w800.jpg",
    "gallery": [
      "/images/unsplash/photo-1514432324607-a09d9b4aefdd_w800.jpg",
      "/images/unsplash/photo-1485955900006-10f4d324d411_w800.jpg"
    ],
    "description": "Seduhan kopi legendaris khas Cikole yang disangrai secara tradisional. Memadukan biji kopi pilihan petani lokal lereng Gunung Tangkuban Parahu dengan cita rasa mantap, aroma smokey yang khas, dan disajikan hangat di tengah sejuknya kabut hutan pinus.",
    "highlights": [
      "Biji Kopi Asli Petani Kaki Gunung Tangkuban Parahu",
      "Sangrai Tradisional Aroma Mantap Smokey",
      "Tersedia Varian Tubruk Klasik, V60, & Kopi Susu Aren",
      "Spot Nongkrong Hangat Favorit Bikers & Wisatawan"
    ],
    "stockQuota": 80,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 31,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-jayagiri-maguru-kopi",
    "title": "Maguru Kopi Legend Jayagiri (Kopi Robusta & Arabika Jayagiri)",
    "category": "minuman-komoditas",
    "price": 15000,
    "unit": "/cangkir",
    "villageId": "des-04",
    "villageName": "Desa Wisata Jayagiri",
    "location": "Pos Kopi Jayagiri, Kaki Gunung Tangkuban Parahu",
    "rating": 4.9,
    "totalReviews": 27,
    "sellerName": "Pa Maliki (Maguru Kopi Jayagiri)",
    "sellerBadge": "Pegiat Kopi Jayagiri",
    "sellerAvatar": "/images/unsplash/photo-1472099645785-5658abf4ff4e_w200.jpg",
    "sellerPhone": "6285717373115",
    "image": "/images/unsplash/photo-1514432324607-a09d9b4aefdd_w800.jpg",
    "gallery": [
      "/images/unsplash/photo-1514432324607-a09d9b4aefdd_w800.jpg"
    ],
    "description": "Kopi seduh legendaris di pintu pendakian Jayagiri yang telah menemani penjelajah alam sejak bertahun-tahun. Disajikan langsung oleh Pa Maliki dengan teknik seduh tradisional yang memanjakan penikmat kopi sejati.",
    "highlights": [
      "Kopi Seduh Otentik Pintu Rimba Jayagiri",
      "Pilihan Arabika Jayagiri & Robusta Pekat",
      "Disajikan Hangat Pas Menemani Suhu Dingin Pegunungan"
    ],
    "stockQuota": 60,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 43,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-gudangkahuripan-gamelan-budaya",
    "title": "Workshop Seni Gamelan Sunda, Tari Tradisional & Literasi Kearifan Lokal",
    "category": "paket-wisata",
    "price": 100000,
    "unit": "/peserta",
    "villageId": "des-07",
    "villageName": "Desa Wisata Gudangkahuripan",
    "location": "Sanggar Seni Budaya Gudangkahuripan, Lembang",
    "rating": 5.0,
    "totalReviews": 31,
    "sellerName": "Pa Mei Wisana (Budayawan Gudangkahuripan)",
    "sellerBadge": "Ketua Sanggar Seni Terverifikasi",
    "sellerAvatar": "/images/unsplash/photo-1519085360753-af0119f7cbe7_w200.jpg",
    "sellerPhone": "6281221520514",
    "image": "/images/unsplash/photo-1513519245088-0e12902e5a38_w800.jpg",
    "gallery": [
      "/images/unsplash/photo-1513519245088-0e12902e5a38_w800.jpg"
    ],
    "description": "Kelas apresiasi seni dan budaya Pasundan interaktif yang dipandu langsung oleh budayawan senior Pa Mei Wisana. Peserta diajak praktik memainkan seperangkat instrumen gamelan degung/salendro, mengenal gerak dasar tari Jaipong, serta menyimak narasi filosofi kearifan lokal masyarakat Lembang zaman ke zaman.",
    "highlights": [
      "Praktik Langsung Menabuh Gamelan Degung Sunda Asli",
      "Pengenalan Gerak Dasar Tari Tradisional Pasundan",
      "Sesi Bincang Literasi Sejarah & Nilai Budaya Lokal",
      "Didampingi Pengrawit & Seniman Senior Desa"
    ],
    "stockQuota": 40,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 53,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-gudangkahuripan-homestay",
    "title": "Homestay Asri Gudangkahuripan (Penginapan Keluarga Khas Pedesaan)",
    "category": "homestay",
    "price": 350000,
    "originalPrice": 400000,
    "unit": "/malam",
    "villageId": "des-07",
    "villageName": "Desa Wisata Gudangkahuripan",
    "location": "Gudangkahuripan, Lembang",
    "rating": 4.8,
    "totalReviews": 24,
    "sellerName": "Pa Joe (Koordinator Homestay Desa)",
    "sellerBadge": "Pengelola Homestay Terverifikasi",
    "sellerAvatar": "/images/unsplash/photo-1506794778202-cad84cf45f1d_w200.jpg",
    "sellerPhone": "6282130532424",
    "image": "/images/real/homestay-gudangkahuripan-asri.jpg",
    "gallery": [
      "/images/real/homestay-gudangkahuripan-asri.jpg",
      "/images/real/homestay-saung-santai.jpg",
      "/images/real/homestay-kamar-keluarga.jpg"
    ],
    "description": "Rumah inap warga bernuansa teduh dan asri di Gudangkahuripan. Memiliki kamar tidur bersih, ruang tamu keluarga, dapur lengkap, serta halaman taman bunga yang nyaman untuk peristirahatan berlibur bersama keluarga.",
    "highlights": [
      "Suasana Asri Tenang dan Nyaman",
      "Kamar Mandi Bersih dengan Water Heater",
      "Dapur Lengkap & Ruang Tamu Luas",
      "Akses Dekat Sentra Kuliner & Wisata Lembang"
    ],
    "facilities": [
      "WiFi Cepat",
      "Water Heater",
      "Dapur & Kulkas",
      "Parkir Mobil Aman",
      "Kopi/Teh Pagi"
    ],
    "stockQuota": 5,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 59,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-wangunsari-tahu-susu",
    "title": "Tahu Susu Lembut Asli Wangunsari (1 Kotak Isi 10 Pcs)",
    "category": "kuliner",
    "price": 25000,
    "unit": "/kotak",
    "villageId": "des-05",
    "villageName": "Desa Wisata Wangunsari",
    "location": "Sentra Tahu Susu Wangunsari, Lembang",
    "rating": 5.0,
    "totalReviews": 65,
    "sellerName": "Pa Agus (Sentra Tahu Susu Wangunsari)",
    "sellerBadge": "Produsen Tahu Susu Binaan",
    "sellerAvatar": "/images/unsplash/photo-1544005313-94ddf0286df2_w200.jpg",
    "sellerPhone": "6285221738102",
    "image": "/images/tahu-susu-goreng.jpg",
    "gallery": [
      "/images/tahu-susu-goreng.jpg"
    ],
    "description": "Tahu susu legendaris produksi Wangunsari Lembang yang terkenal sangat lembut di dalam dan garing renyah di luar saat digoreng. Dibuat dari kedelai non-transgenik pilihan yang dipadukan dengan susu sapi murni segar hasil peternak lokal. Tanpa bahan pengawet.",
    "highlights": [
      "Tekstur Lumer Lembut di Dalam, Garing di Luar",
      "Kandungan Susu Sapi Murni Segar Asli Lembang",
      "Higienis & Bebas Pengawet Berbahaya",
      "Cocok Sebagai Camilan Gurih & Oleh-Oleh Wajib"
    ],
    "stockQuota": 100,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 62,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-wangunsari-kicimpring",
    "title": "Kicimpring Singkong Renyah Gurih Wangunsari (250gr)",
    "category": "kuliner",
    "price": 15000,
    "unit": "/bungkus 250gr",
    "villageId": "des-05",
    "villageName": "Desa Wisata Wangunsari",
    "location": "Wangunsari, Lembang",
    "rating": 4.9,
    "totalReviews": 39,
    "sellerName": "Bu Agustian (UMKM Olahan Singkong)",
    "sellerBadge": "Pengrajin Kicimpring Tradisional",
    "sellerAvatar": "/images/unsplash/photo-1494790108377-be9c29b29330_w150.jpg",
    "sellerPhone": "6282216508602",
    "image": "/images/real/kicimpring.jpg",
    "gallery": [
      "/images/real/kicimpring.jpg"
    ],
    "description": "Kerupuk kicimpring olahan singkong khas Pasundan buatan tangan Bu Agustian. Dipadukan dengan rempah daun bawang, bawang putih, ketumbar, dan cabai merah yang menghasilkan kerenyahan tiada tara dengan cita rasa gurih nagih.",
    "highlights": [
      "100% Singkong Lokal Berkualitas",
      "Bumbu Rempah Daun Bawang Alami",
      "Sangat Renyah, Tidak Keras",
      "Camilan Tradisional Favorit Sepanjang Masa"
    ],
    "stockQuota": 80,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 63,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-wangunsari-ranginang",
    "title": "Ranginang Ketan Renyah Gurih Dapur Bu Entin Wangunsari",
    "category": "kuliner",
    "price": 20000,
    "unit": "/bungkus",
    "villageId": "des-05",
    "villageName": "Desa Wisata Wangunsari",
    "location": "Wangunsari, Lembang",
    "rating": 4.8,
    "totalReviews": 34,
    "sellerName": "Bu Entin (Dapur Ranginang Wangunsari)",
    "sellerBadge": "Pengrajin Ranginang Tradisional",
    "sellerAvatar": "/images/unsplash/photo-1544005313-94ddf0286df2_w200.jpg",
    "sellerPhone": "6287887614185",
    "image": "/images/real/ranginang.jpg",
    "gallery": [
      "/images/real/ranginang.jpg"
    ],
    "description": "Ranginang beras ketan premium pilihan yang diolah secara higienis dengan bumbu terasi gurih khas Sunda. Mekar sempurna saat digoreng, super renyah tanpa meninggalkan rasa lengket di gigi.",
    "highlights": [
      "Beras Ketan Pilihan Hasil Panen Petani",
      "Cita Rasa Gurih Wangi Terasi Alami",
      "Mekar Sempurna & Renyah Maksimal",
      "Tersedia Siap Santap Maupun Mentah"
    ],
    "stockQuota": 60,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 64,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-wangunsari-peuyeum-ketan",
    "title": "Peuyeum Ketan Bungkus Daun Jambu Manis Legi Wangunsari",
    "category": "kuliner",
    "price": 25000,
    "unit": "/ember mini (isi 16 pcs)",
    "villageId": "des-05",
    "villageName": "Desa Wisata Wangunsari",
    "location": "Wangunsari, Lembang",
    "rating": 5.0,
    "totalReviews": 45,
    "sellerName": "Pa Agus Komarudin (Peuyeum Ketan Tradisional)",
    "sellerBadge": "Pembuat Peuyeum Tradisional",
    "sellerAvatar": "/images/unsplash/photo-1507003211169-0a1dd7228f2d_w200.jpg",
    "sellerPhone": "6285222431566",
    "image": "/images/unsplash/photo-1555396273-367ea4eb4db5_w800.jpg",
    "gallery": [
      "/images/unsplash/photo-1555396273-367ea4eb4db5_w800.jpg"
    ],
    "description": "Tape ketan (peuyeum) hitam/putih fermentasi alami yang dibungkus rapi menggunakan daun jambu air segar. Memiliki rasa manis berair (juicy), aroma khas ragi tradisional yang segar, serta tekstur lembut yang sangat nikmat disajikan dingin.",
    "highlights": [
      "Fermentasi Ragi Alami Resep Turun-Temurun",
      "Wangi Daun Jambu Air Segar Alami",
      "Air Tape Manis Segar Menyegarkan Tenggorokan",
      "Dikemas Higienis Ember Mini Praktis & Aman Dibawa"
    ],
    "stockQuota": 50,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 65,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-sukajaya-yoghurt-alami",
    "title": "Yoghurt Probiotik Susu Sapi Murni Sukajaya (Botol 250ml)",
    "category": "olahan-susu",
    "price": 18000,
    "unit": "/botol 250ml",
    "villageId": "des-08",
    "villageName": "Desa Wisata Sukajaya",
    "location": "Sentra Olahan Susu Sukajaya, Lembang",
    "rating": 4.9,
    "totalReviews": 52,
    "sellerName": "Pa Emin (Peternakan Mandiri Sukajaya)",
    "sellerBadge": "Peternak & Pengolah Susu Sukajaya",
    "sellerAvatar": "/images/unsplash/photo-1500648767791-00dcc994a43e_w200.jpg",
    "sellerPhone": "62895322096504",
    "image": "/images/unsplash/photo-1571212515416-fef01fc43637_w800.jpg",
    "gallery": [
      "/images/unsplash/photo-1571212515416-fef01fc43637_w800.jpg"
    ],
    "description": "Yoghurt kental kaya probiotik baik yang diolah langsung dari 100% susu sapi perah segar peternak Sukajaya. Tanpa pewarna sintetis atau pemanis buatan, tersedia dalam varian rasa buah stroberi kebun, blueberry, mangga, dan original plain.",
    "highlights": [
      "Dibuat Dari Susu Sapi Segar Perahan Pagi",
      "Kaya Bakteri Baik Probiotik Menyehatkan Pencernaan",
      "Rasa Manis-Asam Buah Segar Alami",
      "Kemasan Botol Higienis Praktis Dingin Siap Minum"
    ],
    "stockQuota": 80,
    "isAvailable": true,
    "isFeatured": true,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 69,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-sukajaya-susu-murni-segar",
    "title": "Susu Sapi Murni Segar Pasteur Sukajaya (Botol 1 Liter)",
    "category": "olahan-susu",
    "price": 15000,
    "unit": "/liter",
    "villageId": "des-08",
    "villageName": "Desa Wisata Sukajaya",
    "location": "Peternakan Sapi Perah Sukajaya, Lembang",
    "rating": 5.0,
    "totalReviews": 61,
    "sellerName": "Pa Emin (Peternakan Mandiri Sukajaya)",
    "sellerBadge": "Peternak & Pengolah Susu Sukajaya",
    "sellerAvatar": "/images/unsplash/photo-1500648767791-00dcc994a43e_w200.jpg",
    "sellerPhone": "62895322096504",
    "image": "/images/unsplash/photo-1550583724-b2692b85b150_w800.jpg",
    "gallery": [
      "/images/unsplash/photo-1550583724-b2692b85b150_w800.jpg"
    ],
    "description": "Susu sapi segar hasil perahan harian peternak sapi perah lereng Sukajaya. Telah melalui pasteurisasi suhu terjaga untuk membunuh kuman patogen tanpa merusak gizi alami, kalsium, dan rasa gurih alaminya.",
    "highlights": [
      "Susu Perah Segar Murni Tanpa Campuran Air",
      "Pasteurisasi Higienis Aman Dikonsumsi Segera",
      "Tinggi Kalsium, Lemak Baik & Protein Alami",
      "Pengiriman Cepat Terjaga Suhu Dingin"
    ],
    "stockQuota": 100,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 70,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  },
  {
    "id": "real-sukajaya-tahu-susu",
    "title": "Tahu Susu Lembut Sukajaya Olahan Peternak Lokal (1 Kotak)",
    "category": "kuliner",
    "price": 25000,
    "unit": "/kotak",
    "villageId": "des-08",
    "villageName": "Desa Wisata Sukajaya",
    "location": "Sukajaya, Lembang",
    "rating": 4.8,
    "totalReviews": 37,
    "sellerName": "Pa Emin (Peternakan Mandiri Sukajaya)",
    "sellerBadge": "Peternak & Pengolah Susu Sukajaya",
    "sellerAvatar": "/images/unsplash/photo-1500648767791-00dcc994a43e_w200.jpg",
    "sellerPhone": "62895322096504",
    "image": "/images/tahu-susu.jpg",
    "gallery": [
      "/images/tahu-susu.jpg",
      "/images/tahu-susu-goreng.jpg"
    ],
    "description": "Tahu susu lezat khas Sukajaya yang memadukan sari kedelai gurih dan susu sapi segar peternak setempat. Cocok disajikan sebagai hidangan sarapan atau teman minum kopi dan teh sore di pegunungan Lembang.",
    "highlights": [
      "Campuran Susu Murni Peternak Sukajaya",
      "Gurih Alami Tanpa Penyedap Kimiawi Berlebih",
      "Luar Garing Dalam Sangat Lembut",
      "Pilihan Favorit Wisatawan Sukajaya"
    ],
    "stockQuota": 75,
    "isAvailable": true,
    "isFeatured": false,
    "isDummy": false,
    "dataSource": "real",
    "rawSourceRow": 71,
    "verifiedBadge": "Data Riil Mitra Terverifikasi"
  }
];
